// Types

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// Errors
export const ERROR_NETWORK_CONNECTION = 'ERROR_NETWORK_CONNECTION';

// Layout
export const LAYOUT_OPEN = 'LAYOUT_OPEN';
export const LAYOUT_CLOSE = 'LAYOUT_CLOSE';
export const TOGGLE_SIDEBAR_VISIBILITY = 'TOGGLE_SIDEBAR_VISIBILITY';

// Games
export const UPDATE_GAMES = 'UPDATE_GAMES';
export const CONTINUE_GAME = 'CONTINUE_GAME';

// Classes
export const UPDATE_CLASSES = 'UPDATE_CLASSES';
export const ADD_NEW_CLASS = 'ADD_NEW_CLASS';
export const REQUEST_CLASSROOM_DATA = 'REQUEST_CLASSROOM_DATA';
export const REQUEST_CLASSROOM_MEMBERS = 'REQUEST_CLASSROOM_MEMBERS';
export const REQUEST_ALL_CLASSROOM_NOTEBOOKS = 'REQUEST_CLASSROOM_MEMBERS_NOTEBOOKS';
export const UPDATE_CLASSROOM_STUDENTS = 'UPDATE_CLASSROOM_STUDENTS';

// Supervision
export const UPDATE_SUPERVISION = 'UPDATE_SUPERVISION';

// Topic
export const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';
export const CHOOSE_TOPIC = 'CHOOSE_TOPIC';

// Storyline Calls
export const REQUEST_PAGE_CURRENT = 'REQUEST_PAGE_CURRENT';
export const REQUEST_PAGE_TRANSITION = 'REQUEST_PAGE_TRANSITION';

// Exercise State
export const SUBMIT_EXERCISE_STATE = 'SUBMIT_EXERCISE_STATE';

// Updates Page
export const UPDATE_PAGE_STATE = 'UPDATE_PAGE_STATE';
export const PAGE_UPDATE = 'PAGE_UPDATE';
export const TRANSITIONS_UPDATE = 'TRANSITIONS_UPDATE';
export const PAGE_COMPONENTS_UPDATE = 'PAGE_COMPONENTS_UPDATE';
export const GAME_STATE_UPDATE = 'GAME_STATE_UPDATE';

// Dialog
export const DIALOG_UPDATE = 'DIALOG_UPDATE';
export const DIALOG_UPDATE_EXISTING = 'DIALOG_UPDATE_EXISTING';
export const DIALOG_ANSWER = 'DIALOG_ANSWER';

// Notebook
export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK';
export const ADD_PERSONAL_NOTE = 'ADD_PERSONAL_NOTE';
export const CHANGE_PERSONAL_NOTE_STATUS = 'CHANGE_PERSONAL_NOTE_STATUS';

// Mail Component
export const UPDATE_SELECTED_MAIL = 'UPDATE_SELECTED_MAIL';
export const MAIL_LIST_UPDATE = 'MAIL_LIST_UPDATE';
export const MAIL_NOTIFICATION_UPDATE = 'MAIL_NOTIFICATION_UPDATE'; 
export const NEW_MAIL_NOTIFICATION_NUMBER_UPDATE = 'NEW_MAIL_NOTIFICATION_NUMBER_UPDATE';
export const SYNC_MAIL = 'SYNC_MAIL';
export const SAVE_MAIL_REPLY = 'SAVE_MAIL_REPLY';
