/* */

// Types
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';


export const LAYOUT_OPEN = 'LAYOUT_OPEN';
export const LAYOUT_CLOSE = 'LAYOUT_CLOSE';

// Topic
export const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';
export const CHOOSE_TOPIC = 'CHOOSE_TOPIC';

// Storyline Calls
export const REQUEST_PAGE_CURRENT = 'REQUEST_PAGE_CURRENT';
export const REQUEST_PAGE_TRANSITION = 'REQUEST_PAGE_TRANSITION';

// Exercise State
export const SUBMIT_EXERCISE_STATE = 'SUBMIT_EXERCISE_STATE';

// Updates Page
export const UPDATE_PAGE_STATE = 'UPDATE_PAGE_STATE';
export const PAGE_UPDATE = 'PAGE_UPDATE';
export const TRANSITIONS_UPDATE = 'TRANSITIONS_UPDATE';
export const PAGE_COMPONENTS_UPDATE = 'PAGE_COMPONENTS_UPDATE';
export const TOPIC_STATE_UPDATE = 'TOPIC_STATE_UPDATE';

// Dialog
export const DIALOG_UPDATE = 'DIALOG_UPDATE';

// Notebook
export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK';
export const REQUEST_PERSONAL_NOTE = 'REQUEST_PERSONAL_NOTE';
export const UPDATE_PERSONAL_NOTE_LIST = 'UPDATE_PERSONAL_NOTE_LIST';
export const ADD_PERSONAL_NOTE = 'ADD_PERSONAL_NOTE';

// Mail Component
export const MAIL_LIST_UPDATE = 'MAIL_LIST_UPDATE'; 
export const MAIL_NOTIFICATION_UPDATE = 'MAIL_NOTIFICATION_UPDATE'; 
export const NEW_MAIL_NOTIFICATION_NUMBER_UPDATE = 'NEW_MAIL_NOTIFICATION_NUMBER_UPDATE';
export const SYNC_MAIL = 'SYNC_MAIL';
export const SAVE_MAIL_REPLY = 'SAVE_MAIL_REPLY';
